server:
  port: 8081

spring:
  application:
    name: flowgate

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: credit-service
              uri: http://127.0.0.1:9000
              predicates:
                - Path=/credit-service/**
              filters:
                - StripPrefix=1

            - id: auditly
              uri: http://127.0.0.1:8080
              predicates:
                - Path=/auditly/**
              filters:
                - StripPrefix=1

            - id: fineval
              uri: http://127.0.0.1:8000
              predicates:
                - Path=/fineval/**
              filters:
                - StripPrefix=1